# Generated by Django 3.2.4 on 2021-06-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitsoft', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_expense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitsoft.group')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitsoft.user')),
            ],
        ),
    ]
