# Generated by Django 3.2.4 on 2021-06-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitsoft', '0004_rename_expenses_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owes',
        ),
    ]
