# Generated by Django 3.2.4 on 2021-06-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitsoft', '0005_delete_owes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_owes', to='splitsoft.user')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owe_whom', to='splitsoft.user')),
            ],
        ),
    ]
