# Generated by Django 3.2.4 on 2021-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitsoft', '0006_owe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_expense',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='owe',
            name='amount',
            field=models.FloatField(),
        ),
    ]
