# Generated by Django 3.2.4 on 2021-06-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitsoft', '0007_auto_20210629_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='owe',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='splitsoft.group'),
        ),
    ]
